class_name UnitDb
## Loads game/data/units.json (generated by tools/extract_units.py from the original .ets scripts)
## and fills a Blackboard for a given unit at a given card league (1..5).

const UNITS_PATH := "res://game/data/units.json"

static var _units: Dictionary = {}


static func load_units() -> void:
	if not _units.is_empty():
		return
	var file := FileAccess.open(UNITS_PATH, FileAccess.READ)
	assert(file != null, "missing %s, run tools/extract_units.py" % UNITS_PATH)
	_units = JSON.parse_string(file.get_as_text())
	assert(_units is Dictionary and not _units.is_empty(), "units.json is empty or invalid")


static func has_unit(unit_id: String) -> bool:
	load_units()
	return _units.has(unit_id)


static func raw(unit_id: String) -> Dictionary:
	load_units()
	assert(_units.has(unit_id), "unknown unit %s" % unit_id)
	return _units[unit_id]


## Resolve league-dependent arrays ([v1..v5] indexed by league 1..5) to a scalar.
static func resolve(value: Variant, league: int) -> Variant:
	if value is Array and value.size() == 5 and (value[0] is float or value[0] is int):
		return value[clampi(league, 1, 5) - 1]
	return value


## Fill a blackboard with the CreateData values of a unit script.
static func fill_blackboard(bb: Blackboard, unit_id: String, league: int) -> void:
	var data := raw(unit_id)
	var values: Dictionary = data["values"]
	for event in values:
		var by_group: Dictionary = values[event]
		for g in by_group:
			var group := Blackboard.ANY_GROUP if g == "*" else int(g)
			bb.set_value(event, group, resolve(by_group[g], league))
	bb.set_value("collision_radius", Blackboard.ANY_GROUP, data.get("collision_radius", 0.5))
	if data.has("tier"):
		bb.set_value("card_tier", Blackboard.ANY_GROUP, data["tier"])
		bb.set_value("card_kind", Blackboard.ANY_GROUP, data["card_kind"])
		bb.set_value("card_legendary", Blackboard.ANY_GROUP, data.get("legendary", false))
